version: '2'
services:
  app:
    build:
      context: .
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    command: /bin/sh -c "sleep 20 && node server.js"

  mongo:
    image: mongo:2.6
    ports:
      - "27017:27017"

  tests:
    build:
      context: .
    depends_on:
      - app
    command: /bin/sh -c "sleep 30 && npm test"
